// ── Animation DSL ────────────────────────────────────────────────────────────
// The DSL is the single source of truth for a video. It is generated by a local
// Ollama model, editable by the user, and consumed by the deterministic renderer.

export type ScenePosition = 'top' | 'center' | 'bottom' | 'top-center';

export interface BaseScene {
  /** Seconds from the start of the video. */
  startTime: number;
  /** Seconds this scene is on screen. */
  duration: number;
}

export interface CodeScene extends BaseScene {
  type: 'code';
  language: string;
  code: string;
  /** Characters per second while typing in. */
  typingSpeed: number;
  highlightSyntax?: boolean;
  cursorVisible?: boolean;
  fontSize?: number;
  title?: string;
}

export interface TerminalScene extends BaseScene {
  type: 'terminal';
  output: string;
  command?: string;
  prompt?: string;
  typingSpeed: number;
  fontSize?: number;
  sound?: boolean;
}

export interface TextScene extends BaseScene {
  type: 'text';
  content: string;
  position: ScenePosition;
  fontSize?: number;
  color?: string;
  fadeIn?: number;
  fadeOut?: number;
}

export interface ClickScene extends BaseScene {
  type: 'click';
  button: string;
  sound?: boolean;
}

export interface WaitScene extends BaseScene {
  type: 'wait';
}

export interface HighlightScene extends BaseScene {
  type: 'highlight';
  startLine: number;
  endLine: number;
  color?: string;
}

// ── Sprite / template animation ────────────────────────────────────────────────
// A generic, deterministic visual layer: a named template (drawn from canvas
// primitives in lib/templates.ts) whose transform is driven by keyframes. This is
// what lets prompts like "a boy jumping in the air" render without bespoke code.
export type Easing = 'linear' | 'easeInOut' | 'easeInCubic' | 'easeOutCubic' | 'easeOutBack';

/** Which transform channel a keyframe drives. */
export type AnimProp = 'x' | 'y' | 'scaleX' | 'scaleY' | 'rotation' | 'opacity';

export interface Keyframe {
  prop: AnimProp;
  /** For x/y: fraction of width/height (0..1, absolute). scale: multiplier of base
   *  scale (1 = natural). rotation: degrees. opacity: 0..1. */
  from: number;
  to: number;
  /** Seconds relative to the scene's own startTime. */
  start: number;
  duration: number;
  easing?: Easing;
}

export interface SpriteScene extends BaseScene {
  type: 'sprite';
  /** A key registered in lib/templates.ts, e.g. 'boy' | 'ball' | 'cloud'. */
  template: string;
  /** Base anchor position as fractions of width/height (0..1). */
  x: number;
  y: number;
  /** Base size multiplier applied on top of the template's natural size. */
  scale: number;
  /** Free-form template params, e.g. { color: '#22d3ee' }. */
  props: Record<string, any>;
  animations: Keyframe[];
}

export type Scene =
  | CodeScene
  | TerminalScene
  | TextScene
  | ClickScene
  | WaitScene
  | HighlightScene
  | SpriteScene;

export interface AnimationDSL {
  title: string;
  duration: number;
  fps: number;
  width: number;
  height: number;
  backgroundColor: string;
  scenes: Scene[];
}
