// ── Animation DSL ────────────────────────────────────────────────────────────
// The DSL is the single source of truth for a video. It is generated by a local
// Ollama model, editable by the user, and consumed by the deterministic renderer.

export type ScenePosition = 'top' | 'center' | 'bottom' | 'top-center';

export interface BaseScene {
  /** Seconds from the start of the video. */
  startTime: number;
  /** Seconds this scene is on screen. */
  duration: number;
  /** Spoken voiceover for this scene, synthesized locally (Kokoro TTS). */
  narration?: string;
  /** Set by the narration pipeline: seconds the synthesized speech lasts. */
  narrationDuration?: number;
}

export interface CodeScene extends BaseScene {
  type: 'code';
  language: string;
  code: string;
  /** Characters per second while typing in. */
  typingSpeed: number;
  highlightSyntax?: boolean;
  cursorVisible?: boolean;
  fontSize?: number;
  title?: string;
}

export interface TerminalScene extends BaseScene {
  type: 'terminal';
  output: string;
  command?: string;
  prompt?: string;
  typingSpeed: number;
  fontSize?: number;
  sound?: boolean;
}

export interface TextScene extends BaseScene {
  type: 'text';
  content: string;
  position: ScenePosition;
  fontSize?: number;
  color?: string;
  fadeIn?: number;
  fadeOut?: number;
}

export interface ClickScene extends BaseScene {
  type: 'click';
  button: string;
  sound?: boolean;
}

export interface WaitScene extends BaseScene {
  type: 'wait';
}

export interface HighlightScene extends BaseScene {
  type: 'highlight';
  startLine: number;
  endLine: number;
  color?: string;
}

export interface TitleScene extends BaseScene {
  type: 'title';
  text: string;
  subtitle?: string;
  accentColor?: string;
}

/** Code evolving from `before` to `after`: kept lines stay, removed lines
 *  collapse away, added lines are typed in — the core tutorial pattern. */
export interface DiffScene extends BaseScene {
  type: 'diff';
  language: string;
  before: string;
  after: string;
  /** Characters per second while typing added lines. */
  typingSpeed: number;
  fontSize?: number;
  title?: string;
}

// ── Sprite / template animation ────────────────────────────────────────────────
// A generic, deterministic visual layer: a named template (drawn from canvas
// primitives in lib/templates.ts) whose transform is driven by keyframes. This is
// what lets prompts like "a boy jumping in the air" render without bespoke code.
export type Easing = 'linear' | 'easeInOut' | 'easeInCubic' | 'easeOutCubic' | 'easeOutBack';

/** Which transform channel a keyframe drives. */
export type AnimProp = 'x' | 'y' | 'scaleX' | 'scaleY' | 'rotation' | 'opacity';

export interface Keyframe {
  prop: AnimProp;
  /** For x/y: fraction of width/height (0..1, absolute). scale: multiplier of base
   *  scale (1 = natural). rotation: degrees. opacity: 0..1. */
  from: number;
  to: number;
  /** Seconds relative to the scene's own startTime. */
  start: number;
  duration: number;
  easing?: Easing;
}

export interface SpriteScene extends BaseScene {
  type: 'sprite';
  /** A key registered in lib/templates.ts, e.g. 'boy' | 'ball' | 'cloud'. */
  template: string;
  /** Base anchor position as fractions of width/height (0..1). */
  x: number;
  y: number;
  /** Base size multiplier applied on top of the template's natural size. */
  scale: number;
  /** Free-form template params, e.g. { color: '#22d3ee' }. */
  props: Record<string, any>;
  animations: Keyframe[];
}

// ── Card scenes ────────────────────────────────────────────────────────────────
// Full-frame explanatory beats between code sections. Like title cards, an
// active card owns the frame.

export interface BulletsScene extends BaseScene {
  type: 'bullets';
  title?: string;
  /** Short points, revealed one by one in sync with the narration. */
  items: string[];
}

export interface DiagramNode {
  id: string;
  label: string;
  /** Position as fractions of width/height (0..1). */
  x: number;
  y: number;
  color?: string;
}

export interface DiagramEdge {
  from: string;
  to: string;
  label?: string;
}

export interface DiagramScene extends BaseScene {
  type: 'diagram';
  title?: string;
  nodes: DiagramNode[];
  edges: DiagramEdge[];
}

export interface QuoteScene extends BaseScene {
  type: 'quote';
  text: string;
  attribution?: string;
}

export interface BigStatScene extends BaseScene {
  type: 'bigstat';
  /** Headline value, e.g. "10x" or "300ms". Numeric part counts up. */
  value: string;
  label: string;
}

/** Section divider: "01 — Setting up". */
export interface ChapterScene extends BaseScene {
  type: 'chapter';
  number?: number;
  text: string;
}

/** The studio mascot appears and acts — an overlay on the current moment.
 *  With `line` set it points at that line of the visible code panel. */
export interface MascotScene extends BaseScene {
  type: 'mascot';
  action: 'wave' | 'point' | 'think' | 'celebrate' | 'shocked' | 'idle';
  /** 1-based line of the current code panel to aim at (point/look). */
  line?: number;
  /** Which side of the code panel to stand on (default right). */
  side?: 'left' | 'right';
}

/** Interactive checkpoint. The player pauses here and waits for an answer;
 *  in exported video it becomes a timed question → answer reveal. */
export interface QuizScene extends BaseScene {
  type: 'quiz';
  question: string;
  options: string[];
  answerIndex: number;
  explanation?: string;
}

/** One graded check: evaluate `expression` against the learner's code and
 *  compare its printed result to `expected` (both trimmed). */
export interface ChallengeTest {
  expression: string;
  expected: string;
}

/** A real coding challenge (LEAP 3). The player pauses, the learner writes code
 *  in an editor, and it's RUN against `tests`. Progression reflects mastery.
 *  Export renders it as a "try this" card with the solution revealed. */
export interface ChallengeScene extends BaseScene {
  type: 'challenge';
  language: string;
  /** What to build, in one or two sentences. */
  prompt: string;
  /** Scaffold the learner starts from (a signature + TODO). */
  starterCode: string;
  /** A correct solution (used for export reveal and as a fallback). */
  solution: string;
  tests: ChallengeTest[];
  hint?: string;
  /** Short concept tag for the learner model, e.g. "list comprehensions". */
  concept?: string;
}

// ── Concept visualization (LEAP 4) ──────────────────────────────────────────────
// Animate the IDEA behind the code — an array being sorted, a pointer walking, the
// call stack growing, a variable accumulating. One general step-based model covers
// most intro-CS concepts. Each step carries the FULL state (not deltas); the
// renderer tweens between consecutive steps (values pop, pointers glide, stack
// frames push/pop).
export interface VizPointer {
  /** Label shown on the pointer, e.g. "i", "left", "head". */
  name: string;
  /** Which array index it points at. */
  index: number;
}

export interface VizStep {
  /** One short line describing this step (shown on screen, synced to narration). */
  caption?: string;
  /** Full array state at this step (cell values as strings). */
  array?: string[];
  /** Indices to highlight (accent). */
  highlight?: number[];
  /** Two indices being compared (amber). */
  compare?: [number, number];
  /** Indices considered done/sorted (green). */
  done?: number[];
  /** Labeled pointers onto array cells. */
  pointers?: VizPointer[];
  /** Named variables to show as boxes, e.g. { sum: "6", i: "2" }. */
  vars?: Record<string, string>;
  /** Full call/DS stack, bottom → top. */
  stack?: string[];
}

export interface VizScene extends BaseScene {
  type: 'viz';
  title?: string;
  /** Primary focus, a layout hint. */
  vizKind?: 'array' | 'stack' | 'vars';
  steps: VizStep[];
}

export type Scene =
  | CodeScene
  | TerminalScene
  | TextScene
  | ClickScene
  | WaitScene
  | HighlightScene
  | TitleScene
  | DiffScene
  | SpriteScene
  | BulletsScene
  | DiagramScene
  | QuoteScene
  | BigStatScene
  | ChapterScene
  | MascotScene
  | QuizScene
  | ChallengeScene
  | VizScene;

export interface AnimationDSL {
  title: string;
  duration: number;
  fps: number;
  width: number;
  height: number;
  backgroundColor: string;
  /** Kokoro voice id for narration, e.g. "af_heart". */
  voice?: string;
  /** Burn narration subtitles into the frame (default true when narration exists). */
  captions?: boolean;
  scenes: Scene[];
}
